# Generated by Django 2.0.9 on 2020-06-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_userprofile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='slug',
        ),
    ]
